global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'backend_servers'
    static_configs:
      - targets:
          - backend_server1:3000
          - backend_server2:3000
          - backend_server3:3000